apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pranaytechinfo/k8s-deploy_frontend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: altair-config
        volumeMounts:
        - name: frontend-data
          mountPath: /code
      volumes:
      - name: frontend-data
        emptyDir: {}
