apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: pgadmin-secret
        volumeMounts:
        - name: pgadmin-data
          mountPath: /root/.pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}
