apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: dev
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t  
  PGADMIN_DEFAULT_PASSWORD: cHdkcHdk  
  POSTGRES_PASSWORD: c2VjcmV0  
